Repository concourse/atc, pull requests merged in 2018-05, with the labels that each got.

#263 add api to fetch list of versioned resource types
  api/handler.go
  api/present/versioned_resource_types.go
  api/resources_test.go
  api/resourceserver/list_versioned_resource_types.go
  routes.go
  wrappa/api_auth_wrappa.go
  wrappa/api_auth_wrappa_test.go
Labels: enhancement

#276 prometheus: Use counter for db queries
  metric/emitter/prometheus.go
Labels: enhancement

#236 Add Vault Cache and Exponential Backoff for Login
  creds/vault/api_client.go
  creds/vault/cache.go
  creds/vault/cache_test.go
  creds/vault/manager.go
  creds/vault/reauther.go
  creds/vault/reauther_test.go
  creds/vault/vault.go
  creds/vault/vault_factory.go
Labels: efficiency, enhancement, resiliency, security

#275 Add platform label to worker metrics
  api/workerserver/heartbeat.go
  metric/emitter/prometheus.go
  metric/metrics.go
Labels: enhancement

#270 [WIP] Create credhub client lazily.
  creds/credhub/credhub.go
  creds/credhub/credhub_factory.go
  creds/credhub/manager.go
Labels: enhancement, resiliency
