Repository concourse/atc, pull requests merged in 2018-07, with the labels that each got.

#285 remove materialized views, optimize marking of non interceptible builds
  db/build.go
  db/build_factory.go
  db/job.go
  db/job_factory.go
  db/migration/bindata.go
  db/migration/migrations/1530037770_replace_materialized_views_with_joins.down.sql
  db/migration/migrations/1530037770_replace_materialized_views_with_joins.up.sql
  db/pipeline.go
Labels: efficiency, enhancement

#287 Add grace period for one-off build containers
  atccmd/command.go
  db/build_factory.go
  db/build_factory_test.go
  db/db_suite_test.go
  gc/gc_suite_test.go
Labels: enhancement

#283 prometheus: Convert scheduling metrics from gauges to counters
  metric/emitter/prometheus.go
Labels: enhancement

#247 Allow ephemeral workers
  api/workers_test.go
  db/dbfakes/fake_worker.go
  db/dbfakes/fake_worker_lifecycle.go
  db/migration/bindata.go
  db/migration/migrations/1517978531_add_ephemeral_workers.down.sql
  db/migration/migrations/1517978531_add_ephemeral_workers.up.sql
  db/worker.go
  db/worker_factory.go
  db/worker_factory_test.go
  db/worker_lifecycle.go
  db/worker_lifecycle_test.go
  db/worker_test.go
  gc/workercollector.go
  gc/workercollector_test.go
  worker.go
  worker/worker.go
  worker/worker_test.go
  worker/workerfakes/fake_worker.go
Labels: enhancement, operability
