Repository concourse/atc, pull requests merged in 2018-04, with the labels that each got.

#256 Fix Vault token max_ttl renewal issue for auth backends
  creds/vault/manager.go
  creds/vault/vault_factory.go
Labels: enhancement

#262 Credentials provider based on the newly announced AWS SecretsManager
  atccmd/command.go
  creds/secretsmanager/manager.go
  creds/secretsmanager/manager_factory.go
  creds/secretsmanager/manager_test.go
  creds/secretsmanager/secretsmanager.go
  creds/secretsmanager/secretsmanager_factory.go
  creds/secretsmanager/secretsmanager_suite_test.go
  creds/secretsmanager/secretsmanager_test.go
Labels: enhancement, security

#249 Add cookie secure flag.
  atccmd/command.go
Labels: enhancement

#268 Release the lock in case of an error
  db/pipeline_locks.go
Labels: bug

#258 Add BuildLogRetentionCalculator
  atccmd/command.go
  gc/buildlogretentioncalculator.go
  gc/buildlogretentioncalculator_test.go
  gc/buildreaper.go
  gc/buildreaper_test.go
Labels: enhancement

#248 Throw jsonapi 400 instead of empty 500 on resource type not found.
  api/resources_test.go
  api/resourceserver/check.go
  db/resource_cache_factory_test.go
  db/resource_config.go
Labels: enhancement, troubleshooting

#272 Re-enable the build reaper that was inadvertently disabled
  atccmd/command.go
Labels: bug

#265 Set Content-Type to "application/json" where applicable in API
  api/builds_test.go
  api/buildserver/create.go
  api/buildserver/get.go
  api/buildserver/plan.go
  api/buildserver/preparation.go
  api/buildserver/resources.go
  api/config_test.go
  api/configserver/get.go
  api/configserver/save.go
  api/info_test.go
  api/infoserver/info.go
  api/jobs_test.go
  api/jobserver/get.go
  api/jobserver/get_build.go
  api/jobserver/list_inputs.go
  api/pipelineserver/build.go
  api/resources_test.go
  api/resourceserver/get.go
  api/resourceserver/list.go
  api/teams_test.go
  api/teamserver/list.go
  api/teamserver/set.go
  api/volumes_test.go
  api/volumeserver/list.go
  api/workers_test.go
  api/workerserver/heartbeat.go
  api/workerserver/list.go
Labels: enhancement, needs-test
